"use client";
import {useEffect,useState,useRef} from 'react';
import {Play,ArrowUpRight,ArrowRight,Menu,X,MapPin,Clock,Calendar,Ticket,Check,Radio,ChevronLeft,ShieldCheck,Film,BarChart3} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type EventRecord={name:string;at:string};
const LOCATIONS:Record<string,string[]>={Lahore:['Demo • Meridian Cinema','Demo • Nova Picturehouse'],Karachi:['Demo • Harbour Cinema','Demo • Orbit Screens'],Islamabad:['Demo • Skyline Cinema','Demo • Aurora Screens']};
const DATES=['October 30, 2026','October 31, 2026','November 1, 2026','November 2, 2026'];
const TIMES=['14:00','17:30','20:30','23:00'];
const UNAVAILABLE=['A3','A4','B6','C4','C5','D2','E7','F4','F5'];
const PRICE=1200;
const eventNames=['page_view','trailer_play','showtimes_view','showtime_selected','booking_started','seat_selected','mock_payment_started','mock_booking_completed','sample_ticket_viewed'];
const money=(n:number)=>`PKR ${n.toLocaleString('en-US')}`;
function Picker({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;options:string[];disabled?:boolean}){return <div className="field"><label>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue placeholder={`Choose ${label.toLowerCase()}`}/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>}
function Recommendations(){const [genre,setGenre]=useState('Sci-Fi');const films:Record<string,[string,string,string][]>={'Sci-Fi':[['ECHOES OF ORION','A transmission beyond the stars.','01'],['AFTER EARTHLIGHT','The last sunrise is only the beginning.','02'],['ZERO HORIZON','Nothing returns from the edge.','03']],Mystery:[['THE SILENT ARCHIVE','Every missing file has a voice.','04'],['ROOM NINETEEN','One door. Two versions of the truth.','05'],['THE VANISHING HOUR','Someone remembers the missing hour.','06']],Thriller:[['BLACK FREQUENCY','Do not answer the next call.','07'],['NIGHT PROTOCOL','Trust ends at midnight.','08'],['THE FINAL RELAY','One message. No way back.','09']]};return <section id="recommendations" className="section wrap"><div className="section-head"><div><p className="eyebrow">KEEP DISCOVERING</p><h2>You may also like</h2></div><Picker label="Genre preference" value={genre} onChange={setGenre} options={Object.keys(films)}/></div><p className="muted">Fictional demo recommendations matched only to your selected genre.</p><div className="recommend-grid">{films[genre].map(([name,line,no])=><article className="recommend" key={name}><span className="catalogue">CINEBUZZ / {no}</span><Film size={30}/><h3>{name}</h3><p>{line}</p><span className="tiny">{genre} · Fictional movie concept</span></article>)}</div></section>}
export default function Home(){
 const [view,setView]=useState('home'),[menu,setMenu]=useState(false),[trailer,setTrailer]=useState(false),[art,setArt]=useState('');
 const [location,setLocation]=useState(''),[cinema,setCinema]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[seats,setSeats]=useState<string[]>([]),[payment,setPayment]=useState('Credit / Debit Card'),[bookingId,setBookingId]=useState('');
 const [events,setEvents]=useState<EventRecord[]>([]);const started=useRef(false);const completed=useRef(false);
 function track(name:string){setEvents(old=>{const next=[...old,{name,at:new Date().toISOString()}];try{sessionStorage.setItem('cinebuzz-demo-events',JSON.stringify(next))}catch{}return next})}
 useEffect(()=>{if(started.current)return;started.current=true;try{const e=JSON.parse(sessionStorage.getItem('cinebuzz-demo-events')||'[]');if(Array.isArray(e))setEvents(e.filter(x=>eventNames.includes(x.name)&&typeof x.at==='string'))}catch{}track('page_view')},[]);
 function go(next:string){setView(next);setMenu(false);window.scrollTo({top:0,behavior:'instant'});if(next==='showtimes')track('showtimes_view')}
 function homeAnchor(anchor:string){setView('home');setMenu(false);setTimeout(()=>document.getElementById(anchor)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),50)}
 function openTrailer(){setTrailer(true);track('trailer_play')}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:'start_demo_showtime_selection',description:'Open simulated showtime selection. Does not reserve seats or make a booking.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');go('showtimes');return {screen:'showtimes',simulation:true}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 function toggleSeat(s:string){setSeats(old=>old.includes(s)?old.filter(x=>x!==s):[...old,s].sort());track('seat_selected')}
 const summary=<dl className="summary"><div><dt>Movie</dt><dd>THE LAST SIGNAL</dd></div><div><dt>Cinema / location</dt><dd>{cinema.replace('Demo • ','')}<small>{location} · Demo cinema</small></dd></div><div><dt>Date / time</dt><dd>{date}<small>{time} · English · 2h 8m</small></dd></div><div><dt>Seats</dt><dd>{seats.length?seats.join(', '):'Choose your seats'}</dd></div><div><dt>Tickets</dt><dd>{seats.length} × {money(PRICE)}</dd></div><div className="total"><dt>Demo total</dt><dd>{money(seats.length*PRICE)}</dd></div></dl>;
 const counts=(n:string)=>events.filter(e=>e.name===n).length;
 return <><a className="skip" href="#main">Skip to content</a><header className="header"><a className="brand" href="#home" onClick={e=>{e.preventDefault();go('home')}} aria-label="CineBuzz home"><img src="/assets/logo.webp" alt="CineBuzz — More Than Movies"/></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><button onClick={()=>go('home')} className={view==='home'?'active':''}>Discover</button><button onClick={()=>homeAnchor('story')}>The story</button><button onClick={()=>homeAnchor('cast')}>Cast</button><button onClick={()=>homeAnchor('campaign')}>The campaign</button></nav><button className="btn small header-cta" onClick={()=>go('showtimes')}>View showtimes <ArrowUpRight size={16}/></button><button className="menu-btn" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main">
 {view==='home'?<><section id="home" className="hero"><img className="hero-art" src="/assets/hero.webp" alt="The Last Signal artwork featuring Sarah, Ethan and a radio telescope beneath a red signal beam" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy wrap"><p className="eyebrow"><span className="line"/> CINEBUZZ STUDIOS PRESENTS</p><h1>THE LAST<br/><span>SIGNAL</span></h1><p className="tagline">The message came from tomorrow.</p><div className="movie-meta"><span>Sci-Fi Mystery Thriller</span><span>2h 8m</span><span>English</span></div><div className="hero-actions"><button className="btn" onClick={openTrailer}><Play size={17} fill="currentColor"/> Watch trailer</button><button className="btn outline" onClick={()=>go('showtimes')}>View showtimes <ArrowUpRight size={18}/></button></div><p className="release">OCTOBER 30, 2026 <span>•</span> A CINEBUZZ ORIGINAL</p></div><div className="hero-bottom wrap"><span><Radio size={15}/> TRANSMISSION INCOMING</span><a href="#story">Explore the unknown ↓</a><span>Fictional movie · MovieReach prototype</span></div></section>
 <div className="film-strip"><span>ONE SIGNAL.</span><span>ONE DAY AHEAD.</span><span>EVERYTHING CHANGES.</span></div>
 <section id="story" className="section wrap story"><div className="story-image"><img src="/assets/signal.webp" alt="A radio telescope receives a mysterious red transmission" loading="lazy"/><span className="image-caption">INCOMING TRANSMISSION / ORIGIN UNKNOWN</span></div><div className="story-copy"><p className="eyebrow">FEATURED MOVIE / THE STORY</p><h2>Tomorrow is<br/>trying to reach us.</h2><p>A mysterious signal breaks through the silence. Its origin is impossible: tomorrow.</p><p className="muted">Sarah hears it first. Ethan knows more than he reveals. As the transmission draws them closer, one question remains: what happens when the future makes contact?</p><div className="detail-grid"><div><span>DIRECTOR</span><strong>Daniel Carter</strong></div><div><span>STUDIO</span><strong>CineBuzz Studios</strong></div><div><span>GENRE</span><strong>Sci-Fi / Mystery / Thriller</strong></div><div><span>RELEASE</span><strong>October 30, 2026</strong></div></div><button className="text-btn" onClick={openTrailer}>Enter the mystery <ArrowRight size={18}/></button></div></section>
 <section id="cast" className="section wrap"><div className="section-head"><div><p className="eyebrow">TWO PEOPLE. ONE IMPOSSIBLE MESSAGE.</p><h2>Behind the signal</h2></div><p className="muted">Meet the fictional characters.</p></div><div className="cast-grid"><article className="cast-card sarah"><img src="/assets/sarah.webp" alt="Sarah, the established character in the supplied reveal artwork" loading="lazy"/><div><span className="eyebrow">THE FIRST TO HEAR</span><h3>SARAH</h3><p>“She heard the signal first.”</p></div></article><article className="cast-card ethan"><img src="/assets/hero.webp" alt="Ethan as depicted in the supplied Last Signal hero artwork" loading="lazy"/><div><span className="eyebrow">THE ONE WHO KNOWS</span><h3>ETHAN</h3><p>“He knows where the signal came from.”</p></div></article></div></section>
 <section id="trailer" className="section wrap"><div className="section-head"><div><p className="eyebrow">TUNE IN</p><h2>The first transmission</h2></div><span className="muted">Official teaser / trailer</span></div><button className="trailer-stage" onClick={openTrailer} aria-label="Open The Last Signal trailer placeholder"><img src="/assets/hero.webp" alt="The Last Signal trailer artwork" loading="lazy"/><span className="play-circle"><Play fill="currentColor"/></span><span className="trailer-label"><strong>THE LAST SIGNAL</strong><span>TRAILER PREVIEW · FINAL VIDEO COMING SOON</span></span></button></section>
 <section className="section wrap why"><p className="eyebrow">WHY WATCH</p><h2>Some messages change everything.</h2><div className="three-grid"><article><Radio/><h3>An impossible premise</h3><p>A transmission from tomorrow. A mystery that starts with a single sound.</p></article><article><Film/><h3>Made for the big screen</h3><p>Atmospheric sci-fi, shadowed control rooms and a world on the edge of discovery.</p></article><article><Clock/><h3>Suspense in every second</h3><p>Follow Sarah and Ethan into the unknown, without knowing who to trust.</p></article></div></section>
 <section id="campaign" className="section wrap"><div className="section-head"><div><p className="eyebrow">THE SIGNAL IS SPREADING</p><h2>From the transmission</h2></div><span className="muted">Campaign collection</span></div><div className="campaign-grid">{[['signal','Mystery signal teaser'],['sarah','Sarah character reveal'],['countdown','Seven days to go']].map(([a,t])=><button className="campaign-card" key={a} onClick={()=>setArt(a)}><img src={'/assets/'+a+'.webp'} alt={t} loading="lazy"/><span>{t}<ArrowUpRight size={18}/></span></button>)}</div><p className="tiny muted">Fictional campaign artwork. Countdown creative is a campaign sample, not a live countdown.</p></section>
 <section className="booking-banner wrap"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Be there when<br/>the signal arrives.</h2><p>Choose your screening. Experience the mock booking journey.</p></div><button className="btn" onClick={()=>go('showtimes')}>View showtimes <ArrowUpRight size={18}/></button></section><Recommendations/></>:
 view==='analytics'?<section className="wrap flow"><p className="eyebrow">CAMPAIGN MEASUREMENT</p><h1>Follow the signal.</h1><div className="notice">SIMULATED / DEMO DATA — device-local prototype activity only. These are not real campaign results or real ticket sales.</div><div className="kpi-grid">{[['Prototype Visits','page_view'],['Trailer Views','trailer_play'],['Showtime Checks','showtimes_view'],['Mock Booking Starts','booking_started'],['Completed Mock Bookings','mock_booking_completed']].map(([label,key])=><article className="panel kpi" key={key}><span>{label}</span><strong>{counts(key)}</strong><small>Simulated</small></article>)}<article className="panel kpi"><span>Mock Booking Conversion Rate</span><strong>{counts('page_view')?(counts('mock_booking_completed')/counts('page_view')*100).toFixed(1):'0'}%</strong><small>Simulated</small></article></div><div className="panel"><h2>Discovery to completion</h2><p className="muted">Completed mock bookings ÷ prototype visits × 100. Visits count page loads; repeat bookings may produce a rate above 100%.</p>{[['Prototype visits','page_view'],['Trailer interactions','trailer_play'],['Showtime checks','showtimes_view'],['Booking starts','booking_started'],['Booking completions','mock_booking_completed']].map(([label,key])=><div className="bar-row" key={key}><span>{label}</span><div className="bar-track"><div style={{width:Math.max(0,counts(key)/Math.max(1,...eventNames.map(counts))*100)+'%'}}/></div><b>{counts(key)}</b></div>)}</div><div className="panel"><h2>Tracking plan & event log</h2><p className="muted">Source: this browser session. Method: local event counters. Each KPI is the count of its named event. Trailer views count placeholder opens until an actual video is supplied. No names, emails or phone numbers are recorded in analytics.</p><div className="event-list">{eventNames.map(n=><p key={n}><code>{n}</code><span>{counts(n)} · Simulated</span></p>)}</div><h3>Recent demo interactions</h3>{events.slice(-6).reverse().map((e,i)=><p className="log" key={i}><span>{e.name}</span><time>{e.at.slice(11,19)} UTC</time></p>)}</div></section>:
 <section className="wrap flow"><button className="text-btn back" onClick={()=>go(view==='showtimes'?'home':view==='seats'?'showtimes':view==='details'?'seats':view==='payment'?'details':'home')}><ChevronLeft size={17}/> {view==='showtimes'||view==='confirmation'||view==='ticket'?'Back to discovery':'Back'}</button><div className="flow-heading"><div><p className="eyebrow">THE LAST SIGNAL / OCTOBER 30, 2026</p><h1>{({showtimes:'Find your transmission.',seats:'Choose your seats.',details:'Your booking details.',payment:'One last step.',confirmation:'You’re tuned in.',ticket:'Your sample e-ticket.'} as Record<string,string>)[view]}</h1></div><span className="demo-badge"><ShieldCheck size={16}/> DEMO EXPERIENCE</span></div><ol className="steps">{['Showtime','Seats','Details','Mock payment','Confirmation'].map((s,i)=><li className={i<=['showtimes','seats','details','payment','confirmation','ticket'].indexOf(view)?'current':''} key={s}><span>{i+1}</span>{s}</li>)}</ol>
 <div className="notice">Simulated cinemas, seats, prices and bookings. No real transaction or ticket reservation will occur.</div>
 {view==='showtimes'?<div className="booking-grid"><div className="panel"><p className="eyebrow">01 / SELECT YOUR SCREENING</p><h2>Make a night of it.</h2><div className="two-grid"><Picker label="Location" value={location} options={Object.keys(LOCATIONS)} onChange={v=>{setLocation(v);setCinema('');setDate('');setTime('');setSeats([])}}/><Picker label="Cinema" value={cinema} options={LOCATIONS[location]||[]} disabled={!location} onChange={v=>{setCinema(v);setDate('');setTime('');setSeats([])}}/></div><Picker label="Date" value={date} options={DATES} disabled={!cinema} onChange={v=>{setDate(v);setTime('');setSeats([])}}/><fieldset disabled={!date}><legend>Select showtime</legend><div className="time-grid">{TIMES.map(t=><button key={t} className={'choice '+(time===t?'selected':'')} aria-pressed={time===t} onClick={()=>{setTime(t);setSeats([]);track('showtime_selected')}}>{t}<small>2D · English</small></button>)}</div></fieldset><button className="btn full" disabled={!location||!cinema||!date||!time} onClick={()=>{completed.current=false;track('booking_started');go('seats')}}>Continue to booking <ArrowRight size={18}/></button></div><aside className="film-aside"><img src="/assets/signal.webp" alt="The Last Signal mystery teaser poster"/><h3>THE LAST SIGNAL</h3><p>Sci-Fi Mystery Thriller · 2h 8m · English</p><p className="tiny">Demo ticket price from {money(PRICE)}</p></aside></div>:null}
 {view==='seats'?<div className="booking-grid"><div className="panel seat-panel"><p className="eyebrow">02 / FIND YOUR SPOT</p><h2>The best view of tomorrow.</h2><div className="screen">SCREEN</div><div className="seat-map" aria-label="Simulated cinema seat map">{'ABCDEF'.split('').map(row=><div className="seat-row" key={row}><span>{row}</span>{Array.from({length:8},(_,i)=>row+(i+1)).map(s=><button key={s} aria-label={`Seat ${s}${UNAVAILABLE.includes(s)?', unavailable demo seat':''}`} aria-pressed={seats.includes(s)} disabled={UNAVAILABLE.includes(s)} className={'seat '+(seats.includes(s)?'selected':'')} onClick={()=>toggleSeat(s)}>{UNAVAILABLE.includes(s)?'×':seats.includes(s)?'✓':s.slice(1)}</button>)}<span>{row}</span></div>)}</div><div className="legend"><span>□ Available</span><span>✓ Selected</span><span>× Unavailable (demo)</span></div></div><aside className="panel"><h3>Your screening</h3><div aria-live="polite">{summary}</div><button className="btn full" disabled={!seats.length} onClick={()=>go('details')}>Continue to details <ArrowRight size={17}/></button><p className="tiny muted">{seats.length?'All seats and prices are simulated.':'Choose at least one seat to continue.'}</p></aside></div>:null}
 {view==='details'?<div className="booking-grid"><form className="panel" onSubmit={e=>{e.preventDefault();track('mock_payment_started');go('payment')}}><p className="eyebrow">03 / BOOKING DETAILS</p><h2>Who’s joining the signal?</h2><p className="muted">Use sample details. Fields stay in memory only and are discarded when you leave this screen. Nothing is sent to a booking service.</p><label className="field">Full name<input name="fullName" autoComplete="off" placeholder="Alex Demo" required minLength={2} maxLength={80} pattern=".*\S.*\S.*"/></label><label className="field">Email<input name="email" type="email" autoComplete="off" placeholder="alex@example.com" required maxLength={120}/></label><label className="field">Phone<input name="phone" type="tel" autoComplete="off" placeholder="0300 1234567" required pattern="[+]?[0-9][0-9 ]{5,17}[0-9]" title="Enter 7–20 characters using digits, spaces and an optional leading +."/></label><button className="btn full" type="submit">Continue to mock payment <ArrowRight size={17}/></button></form><aside className="panel"><h3>Review your booking</h3>{summary}</aside></div>:null}
 {view==='payment'?<div className="booking-grid"><div className="panel"><p className="eyebrow">04 / DEMO PAYMENT</p><h2>A simulation. Nothing charged.</h2><div className="notice strong">DEMO PAYMENT<br/>NO REAL TRANSACTION WILL OCCUR</div><Picker label="Simulated payment method" value={payment} onChange={setPayment} options={['Credit / Debit Card','Digital Wallet']}/><div className="demo-card"><span>{payment==='Digital Wallet'?'DEMO WALLET':'CINEBUZZ / DEMO CARD'}</span><strong>{payment==='Digital Wallet'?'Demo balance: unlimited':'••••  ••••  ••••  0000'}</strong><small>{payment==='Digital Wallet'?'No account connection required':'SAMPLE CARD · No card details needed'}</small></div><p className="muted">The button below only completes the local prototype flow.</p><button className="btn full" onClick={()=>{if(completed.current)return;setBookingId('DEMO-'+Array.from(crypto.getRandomValues(new Uint8Array(4)),n=>n.toString(16).padStart(2,'0')).join('').toUpperCase());completed.current=true;track('mock_booking_completed');go('confirmation')}}>Complete mock booking <ArrowRight size={17}/></button></div><aside className="panel"><h3>Final review</h3>{summary}</aside></div>:null}
 {view==='confirmation'?<><div className="confirmation panel"><span className="success-mark"><Check size={36}/></span><p className="eyebrow">BOOKING SIMULATION COMPLETE</p><h2>Tomorrow is waiting.</h2><p>Your mock booking for <strong>THE LAST SIGNAL</strong> has been confirmed.</p><p className="reference">{bookingId}</p>{summary}<button className="btn" onClick={()=>{track('sample_ticket_viewed');go('ticket')}}>View sample e-ticket <Ticket size={18}/></button><p className="tiny muted">No payment was taken. No real seats were reserved.</p></div><Recommendations/></>:null}
 {view==='ticket'?<><article className="sample-ticket"><div className="ticket-art"><img src="/assets/signal.webp" alt="The Last Signal teaser artwork"/></div><div className="ticket-body"><img className="ticket-logo" src="/assets/logo.webp" alt="CineBuzz"/><p className="eyebrow">SAMPLE E-TICKET</p><h2>THE LAST SIGNAL</h2><div className="ticket-warning">SAMPLE/DEMO – NOT VALID FOR ENTRY</div>{summary}<p className="reference">{bookingId}</p><p className="tiny">Decorative sample only. No valid admission code or ticket verification exists.</p></div></article><Recommendations/></>:null}
 </section>}
 </main><footer className="footer wrap"><div><img src="/assets/logo.webp" alt="CineBuzz"/><p>Discover. Watch. Belong.</p></div><div><span>CINEBUZZ / MOVIEREACH</span><p>Aptech TechWiz · Digital Marketing Frontiers</p><p className="tiny">Fictional movie promotion and mock booking prototype.</p></div><button className="text-btn" onClick={()=>go('analytics')}><BarChart3 size={17}/> Demo analytics</button></footer>
 <Dialog open={trailer} onOpenChange={setTrailer}><DialogContent className="cinema-dialog"><DialogTitle>THE LAST SIGNAL — Official teaser / trailer</DialogTitle><DialogDescription>Trailer placeholder. The final video has not been supplied.</DialogDescription><img src="/assets/hero.webp" alt="The Last Signal trailer thumbnail"/><div className="notice">FINAL TRAILER COMING SOON<br/><span>This interactive preview is ready for the final MP4. No video is currently playing.</span></div><button className="btn" onClick={()=>{setTrailer(false);go('showtimes')}}>View showtimes <ArrowRight size={17}/></button></DialogContent></Dialog>
 <Dialog open={!!art} onOpenChange={v=>{if(!v)setArt('')}}><DialogContent className="art-dialog"><DialogTitle>Campaign artwork</DialogTitle><DialogDescription>Supplied fictional movie campaign creative.</DialogDescription>{art&&<img src={'/assets/'+art+'.webp'} alt="Full CineBuzz campaign artwork"/>}</DialogContent></Dialog>
 </>;
}
